set -g prefix C-a
unbind C-b
unbind Space
set -g base-index 1
setw -g pane-base-index 1
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"
bind C-a send-prefix
bind | split-window -h
bind - split-window -v
bind C-x setw synchronize-panes
set -g mouse on

set -g status-fg white
set -g status-bg default
set -g status-position top

#set-option history-limit 3000

setw -g window-status-format "#[fg=brightblue]#I #W"
setw -g window-status-current-format "#[fg=white]#I #W"

setw -g window-status-last-style fg=brightblue
setw -g window-status-activity-style fg=green
setw -g window-status-bell-style fg=blue

setw -g window-status-separator ' | '

set -g status-left-length 120
set -g status-right-length 140
set -g status-left "#[fg=black]#[bg=blue] #S#[fg=blue,bg=green]#[bg=green,fg=black]W#I/#{session_windows} P#P/#{window_panes}#[fg=green,bg=yellow]#[fg=black,bg=yellow]#W#[fg=yellow,bg=black] "
set -g status-right "#{?pane_synchronized, #[bg=red]SYNC!!!#[default],} #{prefix_highlight} #(tmux-spotify-info withicon)#[fg=white] | #[fg=brightblue] #(ip addr show dev enp0s25 | grep 'inet[^6]' | awk '{print $2}') #[fg=white]| #[fg=brightblue]#{wifi_ssid} #{wifi_icon} #{online_status}  #[fg=white]| #[fg=cyan]%H:%M #[fg=brightblue]%F #[fg=green]#[bg=black]#[fg=black]#[bg=green]#U@#H#[fg=green,bg=black]"

set-option -g allow-rename off
setw -g automatic-rename off

set -g pane-active-border-bg default
set -g pane-active-border-fg white
set -g pane-border-fg brightblue
set -g pane-border-bg default
setw -g pane-border-format "#{pane_title}: #{pane_current_command}#{?#{!=:#{pane_current_command},ssh}, #{pane_current_path},} (#{pane_width}x#{pane_height})"
setw -g pane-border-status top


set -g message-fg white
set -g message-bg black
set -g message-attr bright

setw -g monitor-activity on
set -g visual-activity off
setw -g mode-keys vi
setw -g main-pane-width 120
# set -g default-command "tmux rename-window zsh; reattach-to-user-namespace -l $SHELL"
set -g default-shell $SHELL

unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind C-p choose-buffer

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDown1Pane select-pane \;\
  send-keys -X copy-pipe "xsel -b -i" \;\
  send-keys -X clear-selection

#bind -t vi-copy 'v' begin-selection
#bind -t vi-copy 'y' copy-selection

set -g @prefix_highlight_fg 'colour04' # default is 'colour231'
set -g @prefix_highlight_bg 'default'  # default is 'colour04'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=yellow,bg=default' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_prefix_prompt 'Wait'
set -g @prefix_highlight_copy_prompt 'Copy'
bind -n C-x setw synchronize-panes
bind C-c run "tmux show-buffer | xsel -b -i"
bind C-v run "tmux set-buffer \"$(xsel -o -b)\"; tmux paste-buffer"

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm,fullscreen'
set -g @resurrect-capture-pane-contents 'on'
set -g @online_icon "#[fg=green]"
set -g @offline_icon "#[fg=red]"
set -g @route_to_ping "herakles.weyhmueller.net"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'soyuka/tmux-current-pane-hostname'
set -g @plugin 'gmoe/tmux-wifi-macos'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-logging'

run '~/.tmux/plugins/tpm/tpm'
