set -g prefix C-a
unbind C-b
unbind Space
set -g base-index 1
setw -g pane-base-index 1
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind C-a send-prefix
bind | split-window -h
bind - split-window -v
set -g mouse on

set -g status-fg white
set -g status-bg default
set -g status-position top
setw -g window-status-fg black
setw -g window-status-bg yellow
setw -g window-status-attr dim
setw -g window-status-current-attr bright
setw -g window-status-format ""
setw -g window-status-separator ''
setw -g window-status-current-format "#[fg=yellow, bg=yellow]⮀#[fg=black, bg=yellow] #I ⮁ #W #[fg=yellow, bg=black]⮀"
setw -g window-status-current-format ""
set -g status-left-length 80
set -g status-right-length 140
set -g status-left "#[fg=black]#[bg=blue]Session: #S#[fg=blue,bg=green]⮀#[bg=green,fg=black]W#I/#{session_windows} P#P/#{window_panes}#[fg=green,bg=yellow]⮀#[fg=black,bg=yellow]#W#[fg=yellow,bg=black]⮀"
set -g status-right "#[fg=#6AE368]#(tmux-spotify-info) #[fg=white]Online: #{online_status} #[fg=cyan]%H:%M:00 #[fg=brightblue]%F #[fg=green]#[bg=black]⮂#[fg=black]#[bg=green]#h#[fg=green,bg=black] "

set-option -g allow-rename off
set -g pane-active-border-bg default
set -g pane-active-border-fg white
set -g pane-border-fg brightblue
set -g pane-border-bg default

set -g message-fg white
set -g message-bg black
set -g message-attr bright

setw -g monitor-activity on
set -g visual-activity off
setw -g mode-keys vi
setw -g main-pane-width 120
set -g default-shell $SHELL

unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'y' copy-selection
bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
bind C-v run "tmux set-buffer \"$(reattach-to-user-namespace pbpaste)\"; tmux paste-buffer"


set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @online_icon "#[fg=green]✓"
set -g @offline_icon "#[fg=red]✗"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
